### ISSUE TITLE
Activating the TextBlurrer plug-in with no text to blur or blank lines causes the browser tab to hang.

### ISSUE THREAD

**Issue by tokawa-ms** [horihiro/TextBlurrer-ChromeExtension#31]
[Issue]
Activating the TextBlurrer plug-in with no text to blur or blank lines causes the browser tab to hang.
ぼかし対象のテキストが何も入力されていないか、もしくはぼかし対象のテキストに空行が含まれている場合、TextBlurrer プラグインを有効化するとブラウザータブがハングアップします。

[Repro Env]
Chrome v.119.0.6045.160 (64bit)
Edge v.119.0.2151.72 (64bit)

[Repro Step (Pattern A)]
1. Install TextBlurrer to your brouser
2. Enable the TextBlurrer plug-in. However, the text to be blurred is left blank and the "Apply" button is applied to the setting.
![image](https://github.com/horihiro/TextBlurrer-ChromeExtension/assets/18474082/97215fe1-47e1-432f-abb2-d82fa210243d)
3. access to https://www.msn.com/
4. jump any link
5. browser tab hang occurs

[Repro Step (Pattern A)]
1. Install TextBlurrer to your brouser
2. Enable the TextBlurrer plug-in. However, one line of text to be blurred is left blank line. and the "Apply" button is applied to the setting.
![image](https://github.com/horihiro/TextBlurrer-ChromeExtension/assets/18474082/ae23c6fa-9221-40fa-8d60-d8568dc2eff0)

3. access to https://www.msn.com/
4. jump any link
5. browser tab hang occurs

**Comment by horihiro** [comment]
Dup of #29 
v0.1.5 で発生するバグ。
暫定対応としては、テキストボックスから空行を削除。

Chrome Extentionでは前バージョンへのロールバックができないので、v0.1.4へのロールバック版をv0.1.6として申請済み。
修正版はv0.1.7として公開予定。

**Comment by horihiro** [comment]
Fixed on [v0.1.7](https://github.com/horihiro/TextBlurrer-ChromeExtension/releases/tag/v0.1.7) and published.
