### ISSUE TITLE
IAMを確認するブレード内でぼかしが有効にならない  

### ISSUE THREAD

**Issue by kkamegawa** [horihiro/TextBlurrer-ChromeExtension#73]
**Describe the bug**
Azureポータル内のIAM確認するブレード内でMSIのリソースIDのサブスクリプションがぼかされません。 

**To Reproduce**
1. IAMブレードを開く(Check access) 
2. Managed Identityを選択する 
3. User assigned managed identityを選ぶ
4. MSIのリソースID内のサブスクリプションIDがぼかされない

**Expected behavior**
リソースID内のサブスクリプションIDがぼかされること

**Screenshots**

https://github.com/user-attachments/assets/540dcf7f-a91d-4251-ad2c-b8d1f1b328dc

**Environment**
- OS: Windows 11 Enterprise 24H2(26120.1252)
- Browser: Edge Version 127.0.2651.74 (Official build) (64-bit)
- Version of this extension: 0.2.5

**Comment by horihiro** [comment]
`/subscription/`ありとなし、どっちでも正規表現でぼかせちゃいますね。

可能でしたら、指定しているパターンをいただけますか？

`/subscription/`あり  
![image](https://github.com/user-attachments/assets/cad5393b-aec7-4983-a67d-31338e7f3a9a)

`/subscription/`なし  
![image](https://github.com/user-attachments/assets/2c552efe-8b5f-4d29-b33f-e440a7ba67de)

**Comment by kkamegawa** [comment]
Copilotに作ってもらいました...

```
GUID（グローバル一意識別子）を検証するための正規表現は以下のようになります：

```regex
^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$
```

この正規表現は、以下の形式のGUIDを検証します：

```
XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
```

- `X` は 0-9 または a-f の16進数文字です。
- 各セクションはハイフンで区切られています。

この正規表現は、GUIDのバージョンとバリアントフィールドも考慮しています¹²³。

```

**Comment by horihiro** [comment]
行頭 '^' と行末 '$' を外してみて、結果が変わるかどうか見てもらえるでしょうか。

**Comment by kkamegawa** [comment]
行頭と行末の文字を消したら消えました！ありがとうございます。
